name: ride_sharing_user_app
description: A ride sharing Flutter project.
version: 2.0.0+11
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.1.2
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  country_code_picker: ^3.0.0
  dotted_border: ^2.1.0
  percent_indicator: ^4.2.3
  url_launcher: ^6.3.0
  flutter_html: ^3.0.0-beta.2
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.10+1
  shimmer_animation: ^2.1.0+1
  file_picker: ^8.0.3
  permission_handler: ^11.3.1
  syncfusion_flutter_datepicker: ^25.2.7
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  flutter_animarker: ^3.2.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  loading_overlay_pro: ^2.1.1
  modal_bottom_sheet: ^3.0.0
  flutter_widget_from_html_core: ^0.14.12
  flutter_typeahead: ^5.2.0
  dotted_line: ^3.2.2
  autocomplete_textfield: ^2.0.1
  web_socket_channel: ^2.4.5
  flutter_inappwebview: ^6.0.0
  firebase_crashlytics: ^4.0.0
  screenshot: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.1
  dart_pusher_channels: ^1.2.2+1
  flutter_switch: ^0.3.2
  just_the_tooltip: ^0.0.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/svg/
    - assets/map/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/font/sf-pro-text-light.ttf
          weight: 300
        - asset: assets/font/sf-pro-text-regular.ttf
          weight: 400
        - asset: assets/font/sf-pro-text-medium.ttf
          weight: 500
        - asset: assets/font/sf-pro-text-semibold.ttf
          weight: 600
        - asset: assets/font/sf-pro-text-bold.ttf
          weight: 700
        - asset: assets/font/sf-pro-text-heavy.ttf
          weight: 900
