// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCD8vu3lfNwrXWyP0CxqBIFyZriKc4-Mg',
    appId: '1:925535730322:web:3ae787ee5850921f3b844b',
    messagingSenderId: '925535730322',
    projectId: 'auser-e7cd9',
    authDomain: 'auser-e7cd9.firebaseapp.com',
    databaseURL: 'https://auser-e7cd9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auser-e7cd9.appspot.com',
    measurementId: 'G-PF5B1RK6M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLn4pTp6AL1p0pXdjKFAiUyOWDWzeKWZc',
    appId: '1:925535730322:android:2bce4261c79a4b1f3b844b',
    messagingSenderId: '925535730322',
    projectId: 'auser-e7cd9',
    databaseURL: 'https://auser-e7cd9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auser-e7cd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM3-aO_unVPofnDa3xuZPvwD2IzeT57gs',
    appId: '1:925535730322:ios:1fa390afe06108243b844b',
    messagingSenderId: '925535730322',
    projectId: 'auser-e7cd9',
    databaseURL: 'https://auser-e7cd9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auser-e7cd9.appspot.com',
    iosClientId: '925535730322-mobnd567jo6ulhop6h91al67s388ilrn.apps.googleusercontent.com',
    iosBundleId: 'com.ashryupp.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM3-aO_unVPofnDa3xuZPvwD2IzeT57gs',
    appId: '1:925535730322:ios:e8f95768289909e93b844b',
    messagingSenderId: '925535730322',
    projectId: 'auser-e7cd9',
    databaseURL: 'https://auser-e7cd9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auser-e7cd9.appspot.com',
    iosClientId: '925535730322-nvcco9rhffib6p3pnlqoi2qsh5old9nl.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.ridesharinguser.rideSharingUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCD8vu3lfNwrXWyP0CxqBIFyZriKc4-Mg',
    appId: '1:925535730322:web:3fbdcba230d0de4a3b844b',
    messagingSenderId: '925535730322',
    projectId: 'auser-e7cd9',
    authDomain: 'auser-e7cd9.firebaseapp.com',
    databaseURL: 'https://auser-e7cd9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auser-e7cd9.appspot.com',
    measurementId: 'G-QB2LJ71RH1',
  );

}